### ISSUE TITLE
Sampler output not as expected

### ISSUE THREAD

**Issue by gunshi** [iwyoo/tf-bilinear_sampler#1]
Hey, i modified test.py like so:

```
import numpy as np
import tensorflow as tf
from bilinear_sampler import bilinear_sampler

x = tf.random_uniform([1, 5, 5, 3])
v = tf.zeros([1, 5, 5, 2])



z,x00 = bilinear_sampler(x, v)

with tf.Session() as sess:
  x_ = sess.run(x)
  z_ ,x00= sess.run([z,x00])
  print(x_)
  print('.........................................................')
  print x00
```
(Also modified bilinear_sampler.py to output x00 along with 'output')

Printing out x00 should just give me the original values of x right?(since flow has zeros)
However the output I get is not what i expect:

[[[[ 0.19786584  0.73615038  0.85592055]
   [ 0.12435114  0.71020055  0.38665438]
   [ 0.24248171  0.38641238  0.78324473]
   [ 0.75399947  0.79320168  0.0474236 ]
   [ 0.23301089  0.63575006  0.80230319]]

  [[ 0.30804241  0.7311784   0.86981308]
   [ 0.6417942   0.65807521  0.21882105]
   [ 0.76683772  0.73147678  0.35990667]
   [ 0.8220613   0.59326911  0.42536461]
   [ 0.86250353  0.7707479   0.11261904]]

  [[ 0.11776614  0.51260507  0.21330643]
   [ 0.66167498  0.62790537  0.43370187]
   [ 0.16098404  0.2746315   0.40525115]
   [ 0.90027165  0.70715988  0.46488118]
   [ 0.45871222  0.82799697  0.0356158 ]]

  [[ 0.85322118  0.58772576  0.82419753]
   [ 0.19227076  0.62972021  0.94120324]
   [ 0.10650766  0.594576    0.40367329]
   [ 0.73168063  0.1661557   0.99791622]
   [ 0.22871339  0.98576617  0.72265947]]

  [[ 0.18727899  0.62645292  0.06143737]
   [ 0.70019412  0.34601188  0.31111419]
   [ 0.66302776  0.90884876  0.1075654 ]
   [ 0.82760906  0.09783912  0.64886224]
   [ 0.32770896  0.21481478  0.54164839]]]]
.....................................................
[[[[ 0.22211611  0.59113646  0.51439822]
   [ 0.661798    0.89728856  0.8142767 ]
   [ 0.4253751   0.99046564  0.87892222]
   [ 0.50606692  0.15366483  0.63259315]
   [ 0.94461513  0.42833197  0.42392766]]

  [[ 0.95639551  0.33327496  0.92829514]
   [ 0.22084379  0.26517344  0.06086767]
   [ 0.21063113  0.95596731  0.45768321]
   [ 0.13467395  0.08498323  0.73405814]
   [ 0.43212819  0.43923008  0.21432722]]

  [[ 0.482903    0.80719292  0.34611917]
   [ 0.63242245  0.01216888  0.89553416]
   [ 0.43385279  0.79077864  0.03036726]
   [ 0.18791544  0.71355999  0.31505632]
   [ 0.49867964  0.10847795  0.06872189]]

  [[ 0.67376828  0.99093592  0.97414815]
   [ 0.78050208  0.84796536  0.37598503]
   [ 0.88365853  0.26032972  0.98525977]
   [ 0.48730075  0.71108067  0.29554653]
   [ 0.45182693  0.93566215  0.29497969]]

  [[ 0.76980674  0.91360664  0.50120091]
   [ 0.66283441  0.16091025  0.66784859]
   [ 0.54449821  0.21315622  0.27560675]
   [ 0.31091094  0.4837935   0.02973545]
   [ 0.57052612  0.6086266   0.06770742]]]]

Is there something I'm missing? Any help would be appreciated
Thanks for the implementation btw!

**Comment by iwyoo** [comment]
The main reason why it gives different values is tf.random~ functions generate random values 'every' session run. If you want to get a same result, then you should get both at same time by
```
x00_, x_ = sess.run([x00, x])
```

**Comment by gunshi** [comment]
Oh I forgot to factor the tf.random call in! Thanks
